name: Automated

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Azure login
      uses: Azure/login@v1.5.1
      with: 
         creds: ${{ secrets.AZURE_CREDENTIAL }}
